# Generated by Django 5.1.3 on 2024-11-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdata',
            name='user',
        ),
    ]
