# Generated by Django 5.1.3 on 2024-12-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatdata',
            options={'verbose_name': 'Chat Data', 'verbose_name_plural': 'Chat Data Entries'},
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='message',
            field=models.CharField(max_length=999991, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='response',
            field=models.CharField(max_length=999991, verbose_name='Response'),
        ),
    ]
