# Generated by Django 5.1.3 on 2024-11-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
