# Generated by Django 5.1.3 on 2024-11-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_title', models.CharField(max_length=255)),
                ('youtube_link', models.URLField(max_length=255)),
                ('generated_content', models.TextField()),
                ('audio_data', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=55)),
                ('user_message', models.TextField()),
                ('llm_response', models.TextField()),
                ('audio_datas', models.BinaryField(blank=True, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('conversations_summary', models.TextField()),
                ('liked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=73)),
                ('user_prompt', models.TextField()),
                ('image_url', models.TextField()),
                ('analysis_text', models.TextField(blank=True, null=True)),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=9991)),
                ('site_image_url', models.TextField()),
                ('tts_url', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('liked', models.IntegerField(default=0)),
                ('user_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
