# Generated by Django 5.1.1 on 2024-09-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=999991)),
                ('response', models.CharField(max_length=999991)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
