# Generated by Django 5.1.1 on 2024-09-23 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_chatdata_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=199, null=True)),
                ('user_message', models.TextField()),
                ('llm_response', models.TextField()),
                ('audio_datas', models.BinaryField(blank=True, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('conversations_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
